//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileInfoExtractor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class ToolTips : global::System.Configuration.ApplicationSettingsBase {
        
        private static ToolTips defaultInstance = ((ToolTips)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ToolTips())));
        
        public static ToolTips Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("국방규격 전산파일명 표기 원칙. SW–[도면번호]-EXE-R[개정차수]")]
        public string tbPathHead {
            get {
                return ((string)(this["tbPathHead"]));
            }
            set {
                this["tbPathHead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("국방규격 전산파일명 표기 원칙. SW–[도면번호]-EXE-R[개정차수]")]
        public string labelPathHead {
            get {
                return ((string)(this["labelPathHead"]));
            }
            set {
                this["labelPathHead"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("파일경로를 모두 대문자로 강제 변경")]
        public string cbUseUpper {
            get {
                return ((string)(this["cbUseUpper"]));
            }
            set {
                this["cbUseUpper"] = value;
            }
        }
    }
}
